"""empty message

Revision ID: c0702782d6ca
Revises: dc884b6f7e17
Create Date: 2018-05-17 08:55:58.753856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0702782d6ca'
down_revision = 'dc884b6f7e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserWordLink',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], )
    )
    op.add_column('words', sa.Column('meaning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'meaning')
    op.drop_table('UserWordLink')
    # ### end Alembic commands ###
